# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from wapps.utils import get_image_model


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0016_auto_20161024_0925'),
        ('blog', '0002_excerpt_as_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=get_image_model()),
        ),
    ]
