# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentitySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('pinterest', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, help_text='The entity public name', max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='A short entity description', max_length=255, null=True, verbose_name='Description')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Identity',
            },
        ),
        migrations.CreateModel(
            name='IdentityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='wapps.IdentitySettings')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wapps_identitytag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='wapps.IdentityTag', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
