# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('wapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='identitysettings',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='wapps.IdentityTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
