# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0004_add_wapps_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitysettings',
            name='logo',
        ),
    ]
