# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from wapps.utils import get_image_model

image_model = get_image_model()


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('wapps', '0005_drop_identity_logo'),
        migrations.swappable_dependency(image_model),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=image_model, verbose_name='Logo'),
        ),
    ]
