# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0007_add_static_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='seo_type',
            field=models.CharField(choices=[('article', 'Article'), ('service', 'Service')], default='article', help_text='What does this page represents', max_length=10, verbose_name='Search engine type'),
        ),
    ]
