# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from wapps.utils import get_image_model

ImageModel = get_image_model()


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='The icon displayed in tab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=ImageModel, verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='favicon_large',
            field=models.ForeignKey(blank=True, help_text='The icon displayed on mobile device and desktop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=ImageModel, verbose_name='Large favicon'),
        ),
    ]
