# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 02:27
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0011_identity_favicons'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysettings',
            name='bg_color',
            field=colorful.fields.RGBColorField(default='#fff', help_text='The background color used to tint the browser', verbose_name='Background color'),
        ),
    ]
