# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0012_identity_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysettings',
            name='svg_logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='SVG Logo'),
        ),
    ]
