# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0013_identitysettings_svg_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysettings',
            name='address_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='address_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address (complement)'),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='identitysettings',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Postal code'),
        ),
    ]
