# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0016_auto_20161024_0925'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
    ]
    run_before = [
        ('wagtailimages', '0014_add_filter_spec_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wappsrendition',
            name='filter_spec',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wappsrendition',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Filter'),
        ),
    ]
