# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:32
from __future__ import unicode_literals

from django.db import migrations

from wagtail.wagtailimages.utils import get_fill_filter_spec_migrations


forward, reverse = get_fill_filter_spec_migrations('wapps', 'WappsRendition')


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0017_upgrade_to_wagtail_1_7'),
        ('wagtailimages', '0015_fill_filter_spec_field'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
