# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0018_new_renditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysettings',
            name='youtube',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
