# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0020_wagtail_18_image_rendition'),
    ]
    run_before = [
        ('wagtailimages', '0018_remove_rendition_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wappsrendition',
            name='filter',
        ),
    ]
