# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapps', '0021_wagtail_19'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='seo_type',
            field=models.CharField(choices=[('article', 'Article'), ('service', 'Service'), ('faq', 'FAQ')], default='article', help_text='What does this page represents', max_length=10, verbose_name='Search engine type'),
        ),
    ]
